/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Uhnuy Kozuki
 */
public class MenuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    private final Connection conn;
    private String idAnggota;
    private String idUser;
    private String idBuku;
    private String idPeminjaman;    
    
    
    public MenuDashboard() {
        initComponents();
        
        conn = Koneksi.getConnection();
        setTabelModel();
        loadData();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardAnggota = new Palette.Custom_JPanelRounded();
        lb_anggota = new javax.swing.JLabel();
        lb_jumlahAnggota = new javax.swing.JLabel();
        lb_iconAnggota = new javax.swing.JLabel();
        cardAnggota1 = new Palette.Custom_JPanelRounded();
        lb_anggota1 = new javax.swing.JLabel();
        lb_jumlahBuku = new javax.swing.JLabel();
        lb_iconAnggota1 = new javax.swing.JLabel();
        cardAnggota2 = new Palette.Custom_JPanelRounded();
        lb_anggota2 = new javax.swing.JLabel();
        lb_jumlahPeminjaman = new javax.swing.JLabel();
        lb_iconAnggota2 = new javax.swing.JLabel();
        cardAnggota3 = new Palette.Custom_JPanelRounded();
        lb_anggota3 = new javax.swing.JLabel();
        lb_jumlahPengembalian = new javax.swing.JLabel();
        lb_iconAnggota3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new Palette.Custom_JTabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1133, 690));

        cardAnggota.setBackground(new java.awt.Color(0, 255, 204));
        cardAnggota.setRoundBottomLeft(30);
        cardAnggota.setRoundBottomRight(30);
        cardAnggota.setRoundTopLeft(30);
        cardAnggota.setRoundTopRight(30);

        lb_anggota.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_anggota.setForeground(new java.awt.Color(153, 153, 153));
        lb_anggota.setText("ANGGOTA");

        lb_jumlahAnggota.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahAnggota.setForeground(new java.awt.Color(0, 102, 153));
        lb_jumlahAnggota.setText("999");

        lb_iconAnggota.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_iconAnggota.setForeground(new java.awt.Color(0, 102, 153));
        lb_iconAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_people_70px.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggotaLayout = new javax.swing.GroupLayout(cardAnggota);
        cardAnggota.setLayout(cardAnggotaLayout);
        cardAnggotaLayout.setHorizontalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_jumlahAnggota)
                    .addComponent(lb_anggota))
                .addGap(50, 50, 50)
                .addComponent(lb_iconAnggota)
                .addGap(20, 20, 20))
        );
        cardAnggotaLayout.setVerticalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_iconAnggota)
                    .addGroup(cardAnggotaLayout.createSequentialGroup()
                        .addComponent(lb_anggota)
                        .addGap(20, 20, 20)
                        .addComponent(lb_jumlahAnggota)))
                .addGap(20, 20, 20))
        );

        cardAnggota1.setBackground(new java.awt.Color(0, 255, 204));
        cardAnggota1.setRoundBottomLeft(30);
        cardAnggota1.setRoundBottomRight(30);
        cardAnggota1.setRoundTopLeft(30);
        cardAnggota1.setRoundTopRight(30);

        lb_anggota1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_anggota1.setForeground(new java.awt.Color(153, 153, 153));
        lb_anggota1.setText("BUKU");

        lb_jumlahBuku.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahBuku.setForeground(new java.awt.Color(0, 102, 153));
        lb_jumlahBuku.setText("999");

        lb_iconAnggota1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_iconAnggota1.setForeground(new java.awt.Color(0, 102, 153));
        lb_iconAnggota1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_book_70px.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggota1Layout = new javax.swing.GroupLayout(cardAnggota1);
        cardAnggota1.setLayout(cardAnggota1Layout);
        cardAnggota1Layout.setHorizontalGroup(
            cardAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cardAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_jumlahBuku)
                    .addComponent(lb_anggota1))
                .addGap(50, 50, 50)
                .addComponent(lb_iconAnggota1)
                .addGap(20, 20, 20))
        );
        cardAnggota1Layout.setVerticalGroup(
            cardAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_iconAnggota1)
                    .addGroup(cardAnggota1Layout.createSequentialGroup()
                        .addComponent(lb_anggota1)
                        .addGap(20, 20, 20)
                        .addComponent(lb_jumlahBuku)))
                .addGap(20, 20, 20))
        );

        cardAnggota2.setBackground(new java.awt.Color(0, 255, 204));
        cardAnggota2.setRoundBottomLeft(30);
        cardAnggota2.setRoundBottomRight(30);
        cardAnggota2.setRoundTopLeft(30);
        cardAnggota2.setRoundTopRight(30);

        lb_anggota2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_anggota2.setForeground(new java.awt.Color(153, 153, 153));
        lb_anggota2.setText("PEMINJAMAN");

        lb_jumlahPeminjaman.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahPeminjaman.setForeground(new java.awt.Color(0, 102, 153));
        lb_jumlahPeminjaman.setText("999");

        lb_iconAnggota2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_iconAnggota2.setForeground(new java.awt.Color(0, 102, 153));
        lb_iconAnggota2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_borrow_book_70px.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggota2Layout = new javax.swing.GroupLayout(cardAnggota2);
        cardAnggota2.setLayout(cardAnggota2Layout);
        cardAnggota2Layout.setHorizontalGroup(
            cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_jumlahPeminjaman)
                    .addComponent(lb_anggota2))
                .addGap(50, 50, 50)
                .addComponent(lb_iconAnggota2)
                .addGap(20, 20, 20))
        );
        cardAnggota2Layout.setVerticalGroup(
            cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_iconAnggota2)
                    .addGroup(cardAnggota2Layout.createSequentialGroup()
                        .addComponent(lb_anggota2)
                        .addGap(20, 20, 20)
                        .addComponent(lb_jumlahPeminjaman)))
                .addGap(20, 20, 20))
        );

        cardAnggota3.setBackground(new java.awt.Color(0, 255, 204));
        cardAnggota3.setRoundBottomLeft(30);
        cardAnggota3.setRoundBottomRight(30);
        cardAnggota3.setRoundTopLeft(30);
        cardAnggota3.setRoundTopRight(30);

        lb_anggota3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_anggota3.setForeground(new java.awt.Color(153, 153, 153));
        lb_anggota3.setText("PENGEMBALIAN");

        lb_jumlahPengembalian.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahPengembalian.setForeground(new java.awt.Color(0, 102, 153));
        lb_jumlahPengembalian.setText("999");

        lb_iconAnggota3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_iconAnggota3.setForeground(new java.awt.Color(0, 102, 153));
        lb_iconAnggota3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_return_book_70px.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggota3Layout = new javax.swing.GroupLayout(cardAnggota3);
        cardAnggota3.setLayout(cardAnggota3Layout);
        cardAnggota3Layout.setHorizontalGroup(
            cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_jumlahPengembalian)
                    .addComponent(lb_anggota3))
                .addGap(50, 50, 50)
                .addComponent(lb_iconAnggota3)
                .addGap(20, 20, 20))
        );
        cardAnggota3Layout.setVerticalGroup(
            cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_iconAnggota3)
                    .addGroup(cardAnggota3Layout.createSequentialGroup()
                        .addComponent(lb_anggota3)
                        .addGap(20, 20, 20)
                        .addComponent(lb_jumlahPengembalian)))
                .addGap(20, 20, 20))
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Riwayat Peminjaman Buku");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Master Data > Dashboard");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_tv_30px.png"))); // NOI18N

        tblData.setForeground(new java.awt.Color(255, 51, 51));
        tblData.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cardAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(cardAnggota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(cardAnggota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(cardAnggota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardAnggota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardAnggota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardAnggota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked


    }//GEN-LAST:event_tblDataMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Custom_JPanelRounded cardAnggota;
    private Palette.Custom_JPanelRounded cardAnggota1;
    private Palette.Custom_JPanelRounded cardAnggota2;
    private Palette.Custom_JPanelRounded cardAnggota3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_anggota;
    private javax.swing.JLabel lb_anggota1;
    private javax.swing.JLabel lb_anggota2;
    private javax.swing.JLabel lb_anggota3;
    private javax.swing.JLabel lb_iconAnggota;
    private javax.swing.JLabel lb_iconAnggota1;
    private javax.swing.JLabel lb_iconAnggota2;
    private javax.swing.JLabel lb_iconAnggota3;
    private javax.swing.JLabel lb_jumlahAnggota;
    private javax.swing.JLabel lb_jumlahBuku;
    private javax.swing.JLabel lb_jumlahPeminjaman;
    private javax.swing.JLabel lb_jumlahPengembalian;
    private Palette.Custom_JTabel tblData;
    // End of variables declaration//GEN-END:variables
    
    private int getTotalDataAnggota(){
        int totalData = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM anggota";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    totalData = rs.getInt("total");
                }
            } 
        } catch (Exception e) {
            Logger.getLogger(MenuPeminjamann.class.getName()).log(Level.SEVERE,null,e);
        }
        
        return totalData;
    }   
    
    private int getTotalDataBuku(){
        int totalData = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM buku";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    totalData = rs.getInt("total");
                }
            } 
        } catch (Exception e) {
            Logger.getLogger(MenuPeminjamann.class.getName()).log(Level.SEVERE,null,e);
        }
        
        return totalData;
    }    
    
    private int getTotalDataPeminjaman(){
        int totalData = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM peminjaman WHERE Status_Peminjaman = 'Dipinjam';";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    totalData = rs.getInt("total");
                }
            } 
        } catch (Exception e) {
            Logger.getLogger(MenuPeminjamann.class.getName()).log(Level.SEVERE,null,e);
        }
        
        return totalData;
    } 
    
    private int getTotalDataPengembalian(){
        int totalData = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM pengembalian";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    totalData = rs.getInt("total");
                }
            } 
        } catch (Exception e) {
            Logger.getLogger(MenuPeminjamann.class.getName()).log(Level.SEVERE,null,e);
        }
        
        return totalData;
    }    
    
    
    private void loadData() {
        getData((DefaultTableModel) tblData.getModel());
        int totalAnggota = getTotalDataAnggota();
        int totalBuku = getTotalDataBuku();
        int totalPeminjaman = getTotalDataPeminjaman();
        int totalPengembalian = getTotalDataPengembalian();
        lb_jumlahAnggota.setText(String.valueOf(totalAnggota));
        lb_jumlahBuku.setText(String.valueOf(totalBuku));
        lb_jumlahPeminjaman.setText(String.valueOf(totalPeminjaman));
        lb_jumlahPengembalian.setText(String.valueOf(totalPengembalian));
    }
    
    private void setTabelModel() {
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        model.addColumn("ID Peminjaman");
        model.addColumn("Tgl Peminjaman");
        model.addColumn("Status Peminjaman");

//        model.addColumn("ID User");
//        model.addColumn("Nama User");
        model.addColumn("ID Anggota");
        model.addColumn("Nama Anggota");
        model.addColumn("ID Buku");
        model.addColumn("Judul Buku");
        model.addColumn("ID Pengembalian");
        model.addColumn("Tgl Pengembalian");
        model.addColumn("Denda Pengembalian");
        
    }

            public void getData(DefaultTableModel model) {
                model.setRowCount(0);
                try {
                    String sql = 
                            "SELECT pm.ID_Peminjaman, pm.Tanggal_Peminjaman, pm.Status_Peminjaman, "+
                            "agt.ID_Anggota, agt.Nama_Anggota,"+
                            "bk.ID_Buku, bk.Judul_Buku,"+
                            "pgm.ID_Pengembalian, pgm.Tanggal_Pengembalian, pgm.Denda_Pengembalian "+
                            "FROM peminjaman pm "+
                            "INNER JOIN anggota agt ON agt.ID_Anggota = pm.ID_Anggota "+
                            "INNER JOIN buku bk ON bk.ID_Buku = pm.ID_Buku "+
                            "INNER JOIN pengembalian pgm ON pgm.ID_Peminjaman = pm.ID_Peminjaman "+
                            "WHERE pm.Status_Peminjaman = 'Sudah Kembali' "+
                            "ORDER BY pm.ID_Peminjaman LIMIT 0, 25";

                    try (PreparedStatement st = conn.prepareStatement(sql)) {
                        ResultSet rs = st.executeQuery();
                        while (rs.next()) {
                            String idPeminjaman = rs.getString("ID_Peminjaman");
                            java.sql.Date tglPinjam = rs.getDate("Tanggal_Peminjaman");
                            String status = rs.getString("Status_Peminjaman");
                            String idAnggota = rs.getString("ID_Anggota");
                            String namaAnggota = rs.getString("Nama_Anggota");
                            String idBuku = rs.getString("ID_Buku");
                            String judulBuku = rs.getString("Judul_Buku");
                            String idPengembalian = rs.getString("ID_Pengembalian");
                            String tglKembali = rs.getString("Tanggal_Pengembalian");
                            String denda = rs.getString("Denda_Pengembalian");

                            // Add data directly to the model
                            Object[] rowData ={idPeminjaman, tglPinjam, status, idAnggota, namaAnggota, idBuku, judulBuku, idPengembalian, tglKembali, denda};
                            model.addRow(rowData);
                        }
                    }
                } catch (SQLException e) {
                    e.printStackTrace();        

        }
    }






}
